package pid389;

import java.util.Arrays;

/**
 * 389. Find the Difference Given two strings s and t which consist of only
 * lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input: s = "abcd" t = "abcde"
 * 
 * Output: e
 * 
 * Explanation: 'e' is the letter that was added.
 * 
 * @author °×
 *
 */
public class main {
	public static void main(String[] args) {
		String[][] testTable = { 
				{"abce",
				"dcbae"},
			};
		for (String[] ito : testTable) {
			test(ito);
		}
	}

	private static void test(String[] ito) {
		System.out.println(Arrays.toString(ito));

		Solution solution = new Solution();
		long begin = System.currentTimeMillis();
		char rtn = solution.findTheDifference(ito[0],ito[1]);
		long end = System.currentTimeMillis();

		System.out.println();
		System.out.println(rtn);
		System.out.println("ºÄÊ±£º" + (end - begin) + "ms");
		System.out.println("--------------");
	}
}
